version: "3.5"
services:
  yoneban:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8090:8080"
    environment:
      - foobar=hey
    volumes:
      - ./prod-database/:/home/gradle/database/
      #      - SERVER_PORT=8080
      #   env_file:
      #     - database.env


